[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 10

[env]
OPENAI_API_KEY = "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"
TWILIO_ACCOUNT_SID = "AC17c88873d670aab4aa4a50fae230d2df"
TWILIO_AUTH_TOKEN = "5c6670d39a1dbf46d47ecdaa244b91d9"
TWILIO_PHONE_NUMBER = "+12182204425"
BACKEND_URL = "https://web-production-f0714.up.railway.app"
COQUI_API_URL = "https://web-production-00dca9.up.railway.app"
HUME_API_KEY = "6h0azxi0FdEbc9CqGyh9MaiK7koK3bLz9JXbBeAUQ7pQNbpN"
HUME_SECRET_KEY = "D97rcH2OacvUOHyKDZ8FS6eNmFLQVgB3RfDvzJYQGoKUS90hgR2C7zJmO7X4czrN"
NODE_ENV = "production"
PORT = "5001"
