[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 10

[env]
OPENAI_API_KEY = "<OPENAI_API_KEY>"
TWILIO_ACCOUNT_SID = "AC17c88873d670aab4aa4a50fae230d2df"
TWILIO_AUTH_TOKEN = "<TWILIO_AUTH_TOKEN>"
TWILIO_PHONE_NUMBER = "+12182204425"
BACKEND_URL = "https://web-production-f0714.up.railway.app"
COQUI_API_URL = "https://web-production-00dca9.up.railway.app"
NODE_ENV = "production"
PORT = "5001"
